import React from 'react';
import {
  Container,
  ScrollView,
  UpdateDate,
  Title,
  SubTitle,
  Text
} from './styles';

export function TermsOfUse() {
  return (
    <Container>
      <ScrollView>
        <UpdateDate>Última alteração: 19/04/2022</UpdateDate>
        <Title>Termos Gerais de Uso</Title>
        <SubTitle>1. Relacionamento Contratual</SubTitle>
        <Text>
          Estes termos de uso (“Termos”) regem seu acesso e uso, como pessoa física, dentro do Brasil, de aplicativos, sites de Internet, conteúdos, bens e também serviços (os “Serviços”) disponibilizados pela Uber do Brasil Tecnologia Ltda., sociedade de responsabilidade limitada, estabelecida no Brasil, com sede na Av. Domingos Odália Filho, 301, 15º andar, Sala 1501, CEP 06010-067, Centro, no município de Osasco/SP, inscrita no CNPJ sob o nº. 17.895.646/0001-87 (“Uber”) ou qualquer de suas afiliadas.{'\n'}
          {'\n'}
          POR FAVOR, LEIA COM ATENÇÃO ESTES TERMOS ANTES DE ACESSAR OU USAR OS SERVIÇOS.{'\n'}
          {'\n'}
          Ao acessar e usar os Serviços você concorda com os presentes termos e condições, que estabelecem o relacionamento contratual entre você, na qualidade de usuário(a), e a Uber. Se você não concorda com estes Termos, você não pode acessar nem usar os Serviços. Mediante referido acesso e uso, estes Termos imediatamente encerram, substituem e superam todos os acordos, Termos e acertos anteriores entre você e qualquer Afiliada da Uber. A Uber poderá imediatamente encerrar estes Termos ou quaisquer Serviços em relação a você ou, de modo geral, deixar de oferecer ou negar acesso aos Serviços ou a qualquer parte deles, a qualquer momento e por qualquer motivo.{'\n'}
          {'\n'}
          Termos adicionais poderão se aplicar a determinados Serviços, tais como condições para um evento, atividade ou promoção em particular, e esses termos adicionais serão divulgados em relação aos respectivos Serviços. Termos adicionais são complementares e considerados parte integrante destes Termos para os efeitos dos respectivos Serviços. Termos adicionais prevalecerão sobre estes Termos em caso de conflito com relação aos referidos Serviços.{'\n'}
          {'\n'}
          A Uber poderá alterar os Termos relativos aos Serviços a qualquer momento. Aditamentos entrarão em vigor quando a Uber fizer a postagem da versão atualizada dos Termos neste local ou das condições atualizadas ou Termos adicionais sobre o respectivo Serviço. O fato de você continuar a acessar ou usar os Serviços após essa postagem representa seu consentimento em vincular-se aos Termos alterados.{'\n'}
          {'\n'}
          A Uber Technologies Inc. é a controladora dos dados pessoais coletados em conexão com o uso dos Serviços no Brasil. Os seus dados pessoais são transferidos para os Estados Unidos da América com base em mecanismos aprovados sob as leis aplicáveis, e a coleta e utilização pela Uber de dados pessoais associados aos Serviços são feitas de acordo com o Aviso de Privacidade da Uber, que pode ser consultada em www.uber.com/privacy.
        </Text>
        <SubTitle>2. Os Serviços</SubTitle>
        <Text>
          Os Serviços integram uma plataforma de tecnologia que permite aos(às) Usuários(as) de aplicativos móveis ou sites de Internet da Uber, fornecidos como parte dos Serviços (cada qual um “Aplicativo”), solicitar e programar serviços de transporte e/ou logística e/ou compra de certos bens com terceiros independentes provedores desses serviços, inclusive terceiros independentes fornecedores de transporte, terceiros independentes fornecedores de logística e terceiros independentes fornecedores de bens, mediante contrato com a Uber ou com determinadas afiliadas da Uber (“Parceiros Independentes”). A menos que diversamente acordado pela Uber em contrato escrito celebrado em separado com você, os Serviços são disponibilizados para seu uso pessoal e não comercial. VOCÊ RECONHECE QUE A UBER NÃO É FORNECEDORA DE BENS, NÃO PRESTA SERVIÇOS DE TRANSPORTE OU LOGÍSTICA, NEM FUNCIONA COMO TRANSPORTADORA, E QUE TODOS ESSES SERVIÇOS DE TRANSPORTE OU LOGÍSTICA SÃO PRESTADOS POR PARCEIROS INDEPENDENTES, QUE NÃO SÃO EMPREGADOS(AS) E NEM REPRESENTANTES DA UBER, NEM DE QUALQUER DE SUAS AFILIADAS.
        </Text>
        <SubTitle>Licença.</SubTitle>
        <Text>
          Sujeito ao cumprimento destes Termos, a Uber outorga a você uma licença limitada, não exclusiva, não passível de sublicença, revogável e não transferível para: (i) acesso e uso dos Aplicativos em seu dispositivo pessoal, exclusivamente para o seu uso dos Serviços; e (ii) acesso e uso de qualquer conteúdo, informação e material correlato que possa ser disponibilizado por meio dos Serviços, em cada caso, para seu uso pessoal, nunca comercial. Quaisquer direitos não expressamente outorgados por estes Termos são reservados à Uber e suas afiliadas licenciadoras.
        </Text>
        <SubTitle>Restrições.</SubTitle>
        <Text>
          Você não poderá: (i) remover qualquer aviso de direito autoral, direito de marca ou outro aviso de direito de propriedade de qualquer parte dos Serviços; (ii) reproduzir, modificar, preparar obras derivadas, distribuir, licenciar, locar, vender, revender, transferir, exibir, veicular, transmitir ou, de qualquer outro modo, explorar os Serviços, exceto da forma expressamente permitida pela Uber; (iii) decompilar, realizar engenharia reversa ou desmontar os Serviços, exceto conforme permitido pela legislação aplicável; (iv) conectar, espelhar ou recortar qualquer parte dos Serviços; (v) fazer ou lançar quaisquer programas ou scripts com a finalidade de sobrecarregar ou prejudicar indevidamente a operação e/ou funcionalidade de qualquer aspecto dos Serviços; ou (vi) tentar obter acesso não autorizado aos Serviços ou prejudicar qualquer aspecto dos Serviços ou seus sistemas ou redes correlatas.
        </Text>
        <SubTitle>Prestação dos Serviços.</SubTitle>
        <Text>
          Você reconhece que os Serviços podem ser disponibilizados sob diferentes marcas da Uber ou diferentes opções de solicitação associadas aos serviços de transporte ou logística prestados por Parceiros Independentes, inclusive marcas de solicitação de transporte atualmente referidas como “Uber”, “UberBLACK”, “uberX”, “UberBAG”; “UberENGLISH”; “UberBIKE”, “Uber Juntos”, e marcas de solicitação de logística atualmente referidas como “UberEATS”, entre outras. Você reconhece também que os Serviços podem estar disponíveis sob essas marcas e opções de solicitação oferecidas por, ou associadas a: (i) determinadas subsidiárias e afiliadas da Uber; ou (ii) Parceiros Independentes, inclusive motoristas de empresas de rede de transporte, detentores(as) de permissão para Serviços de transporte na categoria profissional ou detentores(as) de permissões, autorizações ou licenças de transporte similares.
        </Text>
        <SubTitle>Serviços e Conteúdo de Terceiros(as).</SubTitle>
        <Text>
          Os Serviços poderão ser disponibilizados e acessados em conexão com Serviços e conteúdo de terceiros(as) (inclusive publicidade) que a Uber não controlará. VOCÊ RECONHECE QUE TERMOS DE USO E POLÍTICAS DE PRIVACIDADE DIFERENTES PODERÃO SER APLICÁVEIS AO USO DESSES SERVIÇOS E CONTEÚDO DE TERCEIROS(AS). A UBER NÃO ENDOSSA ESSES SERVIÇOS E CONTEÚDO DE TERCEIROS(AS) E A UBER NÃO SERÁ, EM HIPÓTESE ALGUMA, RESPONSÁVEL POR NENHUM PRODUTO OU SERVIÇO DESSES(AS) TERCEIROS(AS) FORNECEDORES(AS). Além disto, Apple Inc., Google, Inc., Microsoft Corporation ou BlackBerry Limited e/ou suas subsidiárias e afiliadas internacionais serão terceiros(as) beneficiários(as) deste Contrato, caso você acesse os Serviços usando aplicativos desenvolvidos para dispositivos móveis baseados em Apple iOS, Android, Microsoft Windows, ou Blackberry, respectivamente. Esses(as) terceiros(as) beneficiários(as) não são partes deste Contrato e não são responsáveis pela prestação dos Serviços ou por qualquer forma de suporte aos Serviços. Seu acesso aos Serviços usando esses dispositivos está sujeito às condições estabelecidas nos termos de serviços dos respectivos terceiros(as) beneficiários(as).
        </Text>
        <SubTitle>Titularidade.</SubTitle>
        <Text>
          Os Serviços e todos os direitos sobre eles são e permanecerão de propriedade da Uber ou de propriedade das afiliadas da Uber, ou de suas respectivas licenciadoras, conforme o caso. Estes Termos e o uso dos Serviços não lhe outorgam nem lhe conferem qualquer direito: (i) sobre os Serviços, exceto pela licença limitada concedida acima; ou (ii) de usar ou, de qualquer modo, fazer referência a nomes societários, logotipos, nomes de produtos ou de Serviços, marcas comerciais ou marcas de serviço da Uber ou de qualquer licenciadora da Uber.
        </Text>
        <SubTitle>3. Uso dos Serviços</SubTitle>
        <SubTitle>Contas de Usuários.</SubTitle>
        <Text>
          Para utilizar grande parte dos Serviços, você deve registrar-se e manter uma conta pessoal de usuário de Serviços (“Conta”). Você deve ter pelo menos 18 anos para registrar uma Conta. Usuários com idade igual ou superior a 12 anos poderão registrar-se e manter uma Conta desde que tenham sido devidamente representados ou tenham obtido o consentimento de seu(s) responsável(is) legal(is), conforme o procedimento para registro aplicável em cada caso. O registro de Conta exige que a Uber colete determinados dados pessoais, que podem incluir seu nome, endereço, número de telefone celular e data de nascimento, assim como pelo menos um método de pagamento válido (cartão de crédito ou parceiro de pagamento aceito pela Uber). Você concorda em manter informações corretas, completas e atualizadas em sua Conta. Se você não mantiver informações corretas, completas e atualizadas em sua Conta, inclusive se o método de pagamento informado for inválido ou expirado, você poderá ficar impossibilitado(a) de acessar e usar os Serviços ou a Uber poderá resolver estes Termos. Você é responsável por todas as atividades realizadas na sua Conta e concorda em manter sempre a segurança e confidencialidade do nome de usuário e senha da sua Conta. A menos que diversamente permitido pela Uber por escrito, você poderá manter apenas uma Conta.
        </Text>
        <SubTitle>Conduta e Obrigações do Usuário.</SubTitle>
        <Text>
          Você não poderá autorizar terceiros(as) a usar sua Conta ou receber serviços de transporte ou logística dos Parceiros Independentes, salvo se estiverem em sua companhia. Você não poderá ceder, nem de qualquer outro modo transferir, sua Conta a nenhuma outra pessoa ou entidade. Você concorda em cumprir todas as leis aplicáveis quando usar os Serviços e que somente poderá usar os Serviços para finalidades legítimas (por ex. não transportar materiais ilegais ou perigosos). Você não poderá, quando usar os Serviços, causar transtorno, aborrecimento, inconveniente ou danos à propriedade dos Parceiros Independentes ou de qualquer outro terceiro. Em determinadas situações, você poderá ser solicitado(a) a fornecer comprovante de identidade para acessar ou usar os Serviços, e concorda que poderá ter seu acesso ou uso dos Serviços negado caso você se recuse a fornecer um comprovante de identidade.
        </Text>
        <SubTitle>Mensagem de Texto (SMS).</SubTitle>
        <Text>
          Ao criar uma Conta, e tal como estabelecido na Política de Privacidade da Uber, você concorda que os Serviços poderão lhe enviar mensagens de textos (SMS) como parte das operações comerciais regulares para o uso dos Serviços. Você poderá optar por não receber mensagens de texto (SMS) da Uber a qualquer momento, seguindo as instruções indicadas em www.uber.com/unsubscribe/. Você reconhece que optar por não receber as mensagens de texto poderá prejudicar o seu uso dos Serviços.
        </Text>
        <SubTitle>Códigos Promocionais.</SubTitle>
        <Text>
          A Uber poderá, a seu exclusivo critério, criar códigos promocionais que poderão ser resgatados para crédito na Conta ou outras características ou benefícios relacionados aos Serviços e/ou a serviços de Parceiros Independentes, sujeitos a quaisquer condições adicionais que a Uber estabelecer para cada um dos códigos promocionais (“Códigos Promocionais”). Você concorda que Códigos Promocionais: (i) devem ser usados de forma legal para a finalidade e o público a que se destinam; (ii) não devem ser duplicados, de qualquer forma vendidos, transferidos ou disponibilizados ao público em geral (seja por meio de postagem ao público ou qualquer outro método), a menos que expressamente permitido pela Uber; (iii) poderão ser desabilitados pela Uber a qualquer momento por motivos legalmente legítimos, sem que disto resulte qualquer responsabilidade para a Uber; (iv) somente poderão ser usados de acordo com as condições específicas que a Uber estabelecer para esses Código Promocional; (v) não são válidos como dinheiro; e (vi) poderão expirar antes de serem usados. A Uber se reserva o direito de reter ou deduzir créditos ou outras funcionalidades ou vantagens obtidas por meio do uso dos Códigos Promocionais por você ou por outro usuário, caso a Uber apure ou acredite que o uso ou resgate do Código Promocional foi feito com erro, fraude, ilegalidade ou violação às condições do respectivo Código Promocional.
        </Text>
        <SubTitle>Conteúdo Fornecido pelo(a) Usuário(a).</SubTitle>
        <Text>
          A Uber poderá, a seu exclusivo critério, permitir que você ou qualquer pessoa apresente, carregue, publique ou, de qualquer modo, disponibilize para a Uber por meio dos Serviços, conteúdo e informações de texto, áudio ou vídeo, inclusive comentários e feedbacks relacionados aos Serviços, iniciação de solicitação de suporte e registro em concursos e promoções (“Conteúdo de Usuário(a)"). Qualquer Conteúdo de Usuário(a) fornecido por você permanece de sua propriedade. Contudo, ao fornecer Conteúdo de Usuário(a) para a Uber, você outorga a Uber e suas afiliadas uma licença dos direitos autorais sobre o Conteúdo de Usuário em nível mundial, perpétua, irrevogável, transferível, isenta de royalties, e com direito a sublicenciar, usar, copiar, modificar, criar obras derivadas, distribuir, publicar, exibir, executar em público e, de qualquer outro modo, explorar esse Conteúdo de Usuário(a) em todos os formatos e canais de distribuição hoje conhecidos ou desenvolvidos no futuro (inclusive em conexão com os Serviços e com os negócios da Uber e em sites e Serviços de terceiros), sem ulterior aviso a você ou seu consentimento, e sem necessidade de pagamento a você ou a qualquer outra pessoa ou entidade.{'\n'}
          {'\n'}
          Você declara e garante que: (i) é o(a) único(a) e exclusivo(a) proprietário(a) de todo Conteúdo de Usuário(a) ou tem todos os direitos, licenças, autorizações e permissões necessários para outorgar à Uber a licença sobre o Conteúdo de Usuário(a) acima referido; e (ii) nem o Conteúdo de Usuário(a) nem sua apresentação, carregamento, publicação ou outra forma de disponibilização desse Conteúdo de Usuário(a), tampouco o uso do Conteúdo de Usuário(a) pela Uber da forma aqui permitida, infringirão, constituirão apropriação indevida nem violarão propriedade intelectual ou direito de propriedade de terceiros(a), nem direitos de publicidade ou privacidade e também não resultarão na violação de qualquer lei ou regulamento aplicável.{'\n'}
          {'\n'}
          Você concorda em não fornecer Conteúdo de Usuário(a) que seja difamatório, calunioso, injurioso, violento, obsceno, pornográfico, ilegal ou de qualquer modo ofensivo, conforme apuração da Uber a seu critério exclusivo, seja ou não esse material protegido por lei. A Uber poderá, mas não está obrigada a, analisar, monitorar ou remover Conteúdo de Usuário(a), a critério exclusivo da Uber, a qualquer momento e por qualquer motivo, sem nenhum aviso a você.
        </Text>
        <SubTitle>Acesso à Rede e Equipamentos.</SubTitle>
        <Text>
          Você é responsável por obter o acesso a rede de dados necessário para usar os Serviços. As taxas e encargos de sua rede de dados e mensagens poderão se aplicar se você acessar ou usar os Serviços de um dispositivo sem fio e você será responsável por essas taxas e encargos. Você é responsável por adquirir e atualizar os equipamentos e dispositivos necessários para acessar e usar os Serviços e Aplicativos e quaisquer de suas atualizações. A UBER NÃO GARANTE QUE OS SERVIÇOS, OU QUALQUER PARTE DELES, FUNCIONARÃO EM QUALQUER EQUIPAMENTO OU DISPOSITIVO EM PARTICULAR. Além disso, os Serviços poderão estar sujeitos a mau funcionamento e atrasos inerentes ao uso da Internet e de comunicações eletrônicas.
        </Text>
        <SubTitle>4. Pagamento</SubTitle>
        <Text>
          Você entende que os serviços ou bens que você receber de um Parceiro Independente, contratados por meio dos Serviços, poderão ser cobrados (“Preço”). Após você ter recebido serviços ou bens obtidos por meio do uso do Serviço, a Uber facilitará o seu pagamento do respectivo Preço ao Parceiro Independente, agindo na qualidade de agente limitado de cobrança do Parceiro Independente. O pagamento do Preço feito dessa maneira será considerado pagamento feito diretamente por você ao Parceiro Independente. O preço incluirá todos os tributos exigidos por lei. Por favor visite https://www.uber.com/pt-BR/cities/ para obter informações adicionais sobre uma determinada região.{'\n'}
          {'\n'}
          O preço pago por você é final e não reembolsável, a menos que diversamente determinado pela Uber. Você tem o direito de solicitar uma redução no Preço ao Parceiro Independente por serviços ou bens recebidos desse Parceiro Independente no momento em que receber esses serviços ou bens. A Uber responderá de acordo com qualquer solicitação de Parceiro Independente para modificar o Preço de um serviço ou bem em particular. Na máxima extensão permitida pela lei aplicável, a Uber reserva o direito de limitar os Preços cobrados em espécie. Uma vez limitado o valor a ser pago em espécie, você deverá disponibilizar um método alternativo de pagamento. Nas hipóteses em que o pagamento em espécie for um método de pagamento aceito, você poderá escolher receber eventuais valores devidos pelo Parceiro Independente a título de troco na forma de créditos Uber Cash, que poderão ser utilizados para pagamento em novas solicitações de Serviços.{'\n'}
          {'\n'}
          O preço total é devido e deve ser pago imediatamente após a prestação do serviço ou entrega do bem pelo Parceiro Independente e o pagamento será facilitado pela Uber mediante o método de pagamento indicado na sua Conta, após o que a Uber enviará um recibo por e-mail. Se for verificado que o método de pagamento indicado na Conta expirou, é inválido ou não pode ser cobrado, você concorda que a Uber poderá, na qualidade de agente limitado de cobrança do Parceiro Independente, usar um método secundário de cobrança na Conta, se houver.{'\n'}
          {'\n'}
          Na relação entre você e a Uber, a Uber reserva-se o direito de estabelecer, remover e/ou revisar o Preço relativo a todos os serviços ou bens obtidos por meio do uso dos Serviços a qualquer momento, a critério exclusivo da Uber. Ademais, você reconhece e concorda que o Preço aplicável em certas áreas geográficas poderá (i) incluir cobranças, tarifas, taxas, impostos e/ou contribuições governamentais devidas em seu nome, inclusive, tarifas de pedágios ou cobranças de aeroportos, conforme a rota tomada pelo Parceiro Independente, o local de origem e/ou destino da viagem ou, e legislação aplicável e, (ii) aumentar substancialmente quando a oferta de serviços por parte dos Parceiros Independentes for menor do que a demanda por referidos serviços. O pagamento de taxas, impostos e/ou contribuições governamentais, serão de sua responsabilidade e você reembolsará o Parceiro Independente e/ou a Uber por todas tarifas, taxas, impostos e/ou contribuições governamentais pagas em seu nome. Para mais detalhes sobre aumento de Preço em decorrência de aumento substancial da demanda, clique aqui. A Uber envidará esforços razoáveis para informá-lo dos Preços que poderão se aplicar, sendo certo que você será responsável pelo pagamento dos Preços lançados em sua Conta independentemente de estar ciente desses Preços ou de seus valores. A Uber poderá, a qualquer momento, fornecer a certos(as) usuários(as) ofertas e descontos promocionais que poderão resultar em valores diferentes cobrados por Serviços iguais ou similares a outros obtidos por meio do uso dos Serviços, e você concorda que essas ofertas e descontos promocionais, a menos que também oferecidos a você, não terão influência sobre os Preços aplicados. Você poderá optar por cancelar sua solicitação de serviços ou bens de um Parceiro Independente a qualquer momento antes da chegada desse Parceiro Independente, caso em que poderá incidir uma taxa de cancelamento.{'\n'}
          {'\n'}
          Esta estrutura de pagamento se destina a remunerar integralmente os Parceiros Independentes pelos serviços ou bens disponibilizados a você. A Uber não indica nenhuma parcela do pagamento como valor extra ou gratificação aos Parceiros Independentes. Qualquer declaração da Uber (no website da Uber, no Aplicativo ou nos materiais de marketing da Uber) de que o pagamento de valores extras são “voluntários”, “não obrigatórios” e/ou “não incluídos” no pagamento que você faz pelos serviços ou bens prestados não pretende sugerir que a Uber oferece valores adicionais àqueles descritos acima aos Parceiros Independentes. Você compreende e concorda que, embora você seja livre para fazer pagamentos adicionais como valor extra a quaisquer Parceiros Independentes que forneça serviços ou bens por meio dos Serviços, você não tem obrigação de fazê-lo. Valores extras são de caráter voluntário. Após ter recebido os serviços ou bens obtidos por meio dos Serviços, você terá a oportunidade de avaliar sua experiência e fazer comentários adicionais sobre o Parceiro Independente.
        </Text>
        <SubTitle>Taxa de Reparos ou Limpeza.</SubTitle>
        <Text>
          Você será responsável pelos custos de reparos a danos ou pela limpeza de veículos de Parceiros Independentes resultantes do uso dos Serviços por meio da sua Conta que excedam os danos naturais decorrentes do uso (“Reparos ou Limpeza”). Caso um Parceiro Independente relate a necessidade de Reparos ou Limpeza e essa solicitação de Reparos ou Limpeza seja confirmada pela Uber, a critério razoável da Uber, a Uber reserva-se o direito de facilitar o pagamento desses Reparos ou Limpeza em nome do Parceiro Independente usando o método de pagamento indicado em sua Conta. Referidos valores serão transferidos pela Uber ao respectivo Parceiro Independente e não serão reembolsáveis.
        </Text>
        <SubTitle>5. Recusa de Garantia; Limitação de Responsabilidade; Indenização.</SubTitle>
        <SubTitle>Recusa de Garantia.</SubTitle>
        <Text>
          OS SERVIÇOS SÃO PRESTADOS “NO ESTADO” E “COMO DISPONÍVEIS”. A UBER RECUSA TODAS AS DECLARAÇÕES E GARANTIAS, EXPRESSAS, IMPLÍCITAS OU LEGAIS, NÃO EXPRESSAMENTE CONTIDAS NESTES TERMOS, INCLUSIVE AS GARANTIAS IMPLÍCITAS DE COMERCIALIZAÇÃO, ADEQUAÇÃO A UMA FINALIDADE ESPECÍFICA E NÃO INFRINGÊNCIA. ADEMAIS, A UBER NÃO FAZ NENHUMA DECLARAÇÃO NEM DÁ GARANTIA SOBRE A CONFIABILIDADE, PONTUALIDADE, QUALIDADE, ADEQUAÇÃO OU DISPONIBILIDADE DOS SERVIÇOS OU DE QUAISQUER SERVIÇOS OU BENS SOLICITADOS POR MEIO DO USO DOS SERVIÇOS, NEM QUE OS SERVIÇOS SERÃO ININTERRUPTOS OU LIVRES DE ERROS. A UBER NÃO GARANTE A QUALIDADE, ADEQUAÇÃO, SEGURANÇA OU HABILIDADE DE PARCEIROS INDEPENDENTES. VOCÊ CONCORDA QUE TODO O RISCO DECORRENTE DO USO DOS SERVIÇOS E DE QUALQUER SERVIÇO OU BEM SOLICITADO POR MEIO DA TECNOLOGIA SERÁ SEMPRE SEU NA MÁXIMA MEDIDA PERMITIDA PELA LEI APLICÁVEL.
        </Text>
        <SubTitle>Limitação de Responsabilidade.</SubTitle>
        <Text>
          A UBER NÃO SERÁ RESPONSÁVEL POR DANOS INDIRETOS, INCIDENTAIS, ESPECIAIS, PUNITIVOS OU EMERGENTES, INCLUSIVE LUCROS CESSANTES, PERDA DE DADOS, DANOS MORAIS OU PATRIMONIAIS RELACIONADOS, ASSOCIADOS OU DECORRENTES DE QUALQUER USO DOS SERVIÇOS AINDA QUE A UBER TENHA SIDO ALERTADA PARA A POSSIBILIDADE DESSES DANOS. A UBER NÃO SERÁ RESPONSÁVEL POR NENHUM DANO, OBRIGAÇÃO OU PREJUÍZO DECORRENTE DO: (i) SEU USO DOS SERVIÇOS OU SUA INCAPACIDADE DE ACESSAR OU USAR OS SERVIÇOS; OU (ii) QUALQUER OPERAÇÃO OU RELACIONAMENTO ENTRE VOCÊ E QUALQUER PARCEIRO INDEPENDENTE, AINDA QUE A UBER TENHA SIDO ALERTADA PARA A POSSIBILIDADE DESSES DANOS. A UBER NÃO SERÁ RESPONSÁVEL POR ATRASOS OU FALHAS DECORRENTES DE CAUSAS FORA DO CONTROLE RAZOÁVEL DA UBER E, TAMPOUCO, PELA QUALIDADE E INTEGRIDADE DOS BENS DISPONIBILIZADOS POR PARCEIROS INDEPENDENTES. VOCÊ RECONHECE QUE PARCEIROS INDEPENDENTES QUE PRESTAREM SERVIÇOS DE TRANSPORTE SOLICITADOS POR MEIO DE ALGUMAS MARCAS PODERÃO OFERECER SERVIÇOS DE TRANSPORTE DO TIPO "DIVISÃO DE VIAGEM" (RIDESHARING) OU PONTO A PONTO (PEER-TO-PEER).{'\n'}
          {'\n'}
          OS SERVIÇOS DA UBER PODERÃO SER USADOS POR VOCÊ PARA SOLICITAR E PROGRAMAR SERVIÇOS DE TRANSPORTE, BENS OU LOGÍSTICA PRESTADOS POR PARCEIROS INDEPENDENTES, MAS VOCÊ CONCORDA QUE A UBER NÃO TEM RESPONSABILIDADE EM RELAÇÃO A VOCÊ, POR CONTA DE QUALQUER SERVIÇO DE TRANSPORTE, BENS OU LOGÍSTICA REALIZADOS POR PARCEIROS INDEPENDENTES, SALVO SE EXPRESSAMENTE ESTABELECIDA NESTES TERMOS. COMO CONSEQUÊNCIA, A UBER NÃO TEM QUALQUER RESPONSABILIDADE POR ROTAS ADOTADAS POR PARCEIROS INDEPENDENTES OU POR QUAISQUER ITENS PERDIDOS NOS VEÍCULOS DE PARCEIROS INDEPENDENTES.{'\n'}
          {'\n'}
          AS LIMITAÇÕES E RECUSA DE GARANTIAS CONTIDAS NESTA CLÁUSULA 5 NÃO POSSUEM O OBJETIVO DE LIMITAR RESPONSABILIDADES OU ALTERAR DIREITOS DE CONSUMIDOR QUE, DE ACORDO COM A LEI APLICÁVEL, NÃO PODEM SER LIMITADOS OU ALTERADOS.
        </Text>
        <SubTitle>Seguro de Acidentes Pessoais.</SubTitle>
        <Text>
          VOCÊ RECONHECE QUE A UBER MANTÉM SEGURO DE ACIDENTES PESSOAIS DE PASSAGEIROS (APP), COM COBERTURA, NOS TERMOS E LIMITES DA APÓLICE, PARA REEMBOLSO DE DESPESAS MÉDICO-HOSPITALARES, INVALIDEZ PERMANENTE TOTAL OU PARCIAL POR ACIDENTE E MORTE ACIDENTAL, DESDE QUE EM VIAGEM REGULAR PELA PLATAFORMA, E QUE EVENTUAL PAGAMENTO DE INDENIZAÇÃO PELA SEGURADORA A VOCÊ SERÁ FEITO SEM QUALQUER ASSUNÇÃO DE RESPONSABILIDADE PELA UBER E SERÁ DEDUZIDO DE QUALQUER EVENTUAL FUTURA OUTRA INDENIZAÇÃO RECLAMADA DECORRENTE DAQUELE MESMO INCIDENTE.{'\n'}
          {'\n'}
          As informações sobre o Seguro de Acidentes Pessoais de Passageiros podem ser acessadas aqui.
        </Text>
        <SubTitle>Indenização.</SubTitle>
        <Text>
          Você concorda em indenizar e manter a Uber, seus diretores(as), conselheiros(as), empregados(as) e agentes isentos(as) de responsabilidade por todas e quaisquer reclamações, cobranças, prejuízos, responsabilidades e despesas (inclusive honorários advocatícios) decorrentes ou relacionados: (i) ao uso dos Serviços, de serviços ou bens obtidos por meio do uso dos Serviços; (ii) descumprimento ou violação de qualquer disposição destes Termos; (iii) o uso, pela Uber, do Conteúdo de Usuário(a); ou (iv) violação dos direitos de terceiros, inclusive Parceiros Independentes.
        </Text>
        <SubTitle>6. Solução de controvérsias</SubTitle>
        <Text>
          A Uber disponibiliza uma estrutura de atendimento, composta por ferramentas de contato e uma equipe especializada de suporte para o tratamento de reclamações com o objetivo de evitar a judicialização de controvérsias que, eventualmente, possam surgir com o seu uso dos Serviços.{'\n'}
          {'\n'}
          Diante disso, você se compromete a utilizar as ferramentas de suporte disponibilizadas pela Uber como primeiro meio para a solução de controvérsias decorrentes do seu uso dos Serviços.{'\n'}
          {'\n'}
          Você também poderá buscar a solução de controvérsias por meio do serviço www.consumidor.gov.br, mantido pela Secretaria Nacional do Consumidor (SENACON) do Ministério da Justiça e Segurança Pública, que é disponibilizado gratuitamente aos consumidores de todo o país com o objetivo de prevenir e reduzir a quantidade de controvérsias judicializadas.
        </Text>
        <SubTitle>7. Legislação Aplicável; Jurisdição.</SubTitle>
        <Text>
          Estes Termos serão regidos e interpretados exclusivamente de acordo com as leis do Brasil. Qualquer reclamação, conflito ou controvérsia que surgir deste contrato ou a ele relacionada, inclusive que diga respeito a sua validade, interpretação ou exequibilidade, será solucionada exclusivamente pelos tribunais do foro de seu domicílio.
        </Text>
        <SubTitle>8. Outras Disposições</SubTitle>
        <SubTitle>Alegações de Violação de Direito Autoral.</SubTitle>
        <Text>
          Alegações de violação de direito autoral devem ser encaminhadas ao representante indicado pela Uber. Consulte a página de Internet da Uber em https://www.uber.com/legal para obter o endereço indicado e outras informações.
        </Text>
        <SubTitle>Avisos.</SubTitle>
        <Text>
          A Uber poderá enviar avisos por meio de notificações gerais nos Serviços, correio eletrônico para seu endereço de e-mail em sua Conta, ou por comunicação escrita enviada ao endereço indicado em sua Conta. Você poderá notificar a Uber por meio do Aplicativo, comunicação pelo endereço eletrônico help.uber.com ou fazer comunicação escrita para o endereço da Uber na Av. Domingos Odália Filho, 301, 15º andar, Sala 1501, CEP 06010-067, Centro, no município de Osasco/SP, Brasil.
        </Text>
        <SubTitle>Disposições Gerais.</SubTitle>
        <Text>
          Você não poderá ceder, nem tampouco transferir estes Termos, total ou parcialmente, sem prévia aprovação por escrito da Uber. Você concorda que a Uber ceda e transfira estes Termos, total ou parcialmente, inclusive: (i) para uma subsidiária ou afiliada; (ii) um adquirente das participações acionárias, negócios ou bens da Uber; ou (iii) para um sucessor em razão de qualquer operação societária. Não existe joint-venture, sociedade, emprego ou relação de representação entre você, a Uber ou quaisquer Parceiros Independentes como resultado do contrato entre você e a Uber ou pelo uso dos Serviços.{'\n'}
          {'\n'}
          Caso qualquer disposição destes Termos seja tida como ilegal, inválida ou inexequível total ou parcialmente, por qualquer legislação, essa disposição ou parte dela será, naquela medida, considerada como não existente para os efeitos destes Termos, mas a legalidade, validade e exequibilidade das demais disposições contidas nestes Termos não serão afetadas. Nesse caso, as partes substituirão a disposição ilegal, inválida ou inexequível, ou parte dela, por outra que seja legal, válida e exequível e que, na máxima medida possível, tenha efeito similar à disposição tida como ilegal, inválida ou inexequível para fins de conteúdo e finalidade dos presentes Termos. Estes Termos constituem a totalidade do acordo e entendimento das partes sobre este assunto e substituem e prevalecem sobre todos os entendimentos e compromissos anteriores sobre este assunto. Nestes Termos, as palavras “inclusive” e “inclui” significam “incluindo, sem limitação”.
        </Text>
      </ScrollView>

    </Container >
  );
}